services:
  - type: web
    name: ckpcet-chatbot
    env: python
    buildCommand: ./render-build.sh
    startCommand: gunicorn --bind 0.0.0.0:$PORT --chdir backend app:app
    envVars:
      - key: OPENROUTER_API_KEY
        sync: false
      - key: OPENROUTER
        value: ON
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ
        value: OFF
      - key: FLASK_ENV
        value: production

